### ISSUE TITLE
personIdentiferType's maximum value seems wrong

### ISSUE THREAD

**Issue by sevein** [JiscRDSS/rdss-message-api-specification#116]
In `v3.0.0` (ce7edb429276c6e7e90d99f5a890f4f2ee0aad40), the `personIdentifierType` taxonomy was updated to list only two terms:

https://github.com/JiscRDSS/rdss-message-api-specification/blob/03675751c0785d2d5afcba3e1b1d1c3ea408862b/schemas/enumeration.json#L125-L130

However also since `v3.0.0`, a different commit (c9c6230d4b74fc846024f4a57510109502c63315) changed the `personIdentifierType` attribute of the `personIdentifier` object so the biggest integer accepted is `6` (five possible terms). I think that it should be `3` instead because the taxonomy only contains two terms.

**Comment by danielgrant** [comment]
Hi @sevein,

The maximum and minimum values of any enumeration type given in the JSON schemas reflect the minimum and maximum ID's of the values for the respective taxonomy in the Taxonomy Schema, i.e. https://github.com/JiscRDSS/taxonomyschema/blob/feature/rdss-2025_update_3_0_0_cdm/datamodels/personIdentifierType.json.

In this case, the data model was simplified in `3.0.0` and a number of values removed the `personIdentifierType` taxonomy. We don't want to re-use ID's in the taxonomy, to avoid causing confusion / conflicts in existing systems that store these ID's, therefore while there are only two values in the `personIdentifierType`, the minimum and maximum range of those values is `1` to `6`.

It's possible we could refine the JSON schema here by using `"enum": [1, 6]` instead of a numerical range though...

**Comment by sevein** [comment]
That makes sense! Thank you.
